scrape_configs:
  - job_name: 'User Authorization Service input'
    metrics_path: '/api/auth/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8081']
        labels:
          application: 'User Authorization Service'